name: Build and Publish to GHCR

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set image name
        id: meta
        run: echo "IMAGE=ghcr.io/${{ github.repository_owner }}/palworld-server" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build -t $IMAGE:latest .

      - name: Push image
        run: |
          docker push $IMAGE:latest
